# Generated by Django 2.0.6 on 2018-06-19 17:29

from django.conf import settings
import django.contrib.gis.geos.point
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import location_field.models.spatial


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('location', location_field.models.spatial.LocationField(default=django.contrib.gis.geos.point.Point(1.0, 1.0), srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=25, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('rating', models.FloatField(default=5.0)),
                ('num_rides', models.IntegerField(default=0)),
                ('phone_num', models.BigIntegerField(blank=True, unique=True)),
                ('friendlist', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RidePosting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('time_min', models.TimeField(db_index=True)),
                ('time_max', models.TimeField(db_index=True, default=models.TimeField(db_index=True))),
                ('price', models.FloatField()),
                ('seats', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('stops', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), size=100)),
                ('confirmed_riders', models.ManyToManyField(related_name='Rides', to=settings.AUTH_USER_MODEL)),
                ('dest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides_from', to='rides.Place')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RidePosts', to=settings.AUTH_USER_MODEL)),
                ('potential_riders', models.ManyToManyField(related_name='Ride_Offers', to=settings.AUTH_USER_MODEL)),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides_to', to='rides.Place')),
            ],
        ),
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('time_min', models.TimeField()),
                ('time_max', models.TimeField()),
                ('seatsNeeded', models.IntegerField(default=1)),
                ('requestCompleted', models.BooleanField(default=False)),
                ('dest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='rides.Place', verbose_name='Destination')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riderrequests', to=settings.AUTH_USER_MODEL, verbose_name='The rider taking the ride')),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start', to='rides.Place', verbose_name='Starting city')),
            ],
        ),
    ]
